theme: jekyll-theme-cayman
title: Timmy
description: Pascal unit for creating chat bots
show_downloads: true
github.zip_url: http://github.com/42tm/timmy/archive/v1.2.0.zip
github.tar_url: http://github.com/42tm/timmy/archive/v1.2.0.tar.gz
